### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by NxtFeier** [HimbeersaftLP/VIP-Commands#2]
Mach doch Argumente zb /fly on ;)
Nur eine Idee :D

**Comment by NxtFeier** [comment]
Falls du nicht weißt wie das geht kann ich dir helfen :D

**Comment by HimbeersaftLP** [comment]
Was hätte das für nen Vorteil gegenüber toggling?

**Comment by HimbeersaftLP** [comment]
Issue wird geschlossen wegen ausstehender Antwort, melde dich, falls du noch immer interessiert bist
